# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: HSS Pack 229

# Below the site title
tagline: Cub Scout Pack 229 @ Holy Spirit School

# Site logo
logo:

# A description of your site for social meta tag, search engines, and feed.xml
description: Cub Scout Pack 229 @ Holy Spirit School, San Jose, CA


# The base hostname & protocol of your site for where absolute urls are needed
url: https://hsspack229.org

# The subpath of your site, if you want to host your path on a subpath like on GitHub Pages. e.g. /blog
baseurl:

sass:
  sass_dir: _sass

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Joining
  url: /joining/
- text: Archives
  url: /tags/

# Author information - author info at the bottom of the post
author_name: "Pack 229"
author_bio: "Cub Scout Pack 229 @ Holy Spirit School"
author_url: "https://hsspack229.org"
author_location: "San Jose, California"
author_image: authorimage.jpg

# Footer ad banner
# banner_image: banner.jpg
# banner_url: https://justgoodthemes.com/

# Footer newsletter widget - add your form action url for MailChimp signup form here
# mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
# twitter_username: "username"
# facebook_username: "username"
# github_username: "username"
# codepen_username: "username"
# dribbble_username: "username"
# medium_username: "@username"
# instagram_username: "username"
# pinterest_username: "username"
# linkedin_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: '/post/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
